In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulary size     
vocab_size = 10000

In [5]:
# one hot representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[8992, 3567, 9062, 5916],
 [8992, 3567, 9062, 4923],
 [8992, 6019, 9062, 1763],
 [965, 6229, 6486, 1397, 3144],
 [965, 6229, 6486, 1397, 5779],
 [593, 8992, 2618, 9062, 1643],
 [2292, 8970, 1420, 1397]]

In [8]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 8992, 3567, 9062, 5916],
       [   0,    0,    0,    0, 8992, 3567, 9062, 4923],
       [   0,    0,    0,    0, 8992, 6019, 9062, 1763],
       [   0,    0,    0,  965, 6229, 6486, 1397, 3144],
       [   0,    0,    0,  965, 6229, 6486, 1397, 5779],
       [   0,    0,    0,  593, 8992, 2618, 9062, 1643],
       [   0,    0,    0,    0, 2292, 8970, 1420, 1397]], dtype=int32)

In [10]:
# feature representation
dim = 10

In [26]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_shape = (sent_length,)))
model.build(input_shape=(None, sent_length)) # Explicitly build the model
model.compile(optimizer='adam', loss='mse')

/Users/navdeep/Desktop/Gen AI/Coding Practice/03. SimpleRNN Project Implementation/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [27]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[[-0.02726716,  0.0405775 ,  0.04777193, -0.02506368,
          0.00904207, -0.04624856,  0.04105926,  0.04074803,
         -0.00436481,  0.00827692],
        [-0.02726716,  0.0405775 ,  0.04777193, -0.02506368,
          0.00904207, -0.04624856,  0.04105926,  0.04074803,
         -0.00436481,  0.00827692],
        [-0.02726716,  0.0405775 ,  0.04777193, -0.02506368,
          0.00904207, -0.04624856,  0.04105926,  0.04074803,
         -0.00436481,  0.00827692],
        [-0.02726716,  0.0405775 ,  0.04777193, -0.02506368,
          0.00904207, -0.04624856,  0.04105926,  0.04074803,
         -0.00436481,  0.00827692],
        [ 0.01432521, -0.04660199,  0.01498565,  0.00469976,
         -0.01096569, -0.04995788, -0.0238113 , -0.02766985,
          0.04284186, -0.02751378],
        [ 0.03806374, -0.00475997, -0.02056726,  0.04164689,
          0.01130963,  0.00706343,  0.02284673, -0.00951695,
          0.03543686, -0.02467113],
        [ 0.00371302, -0.03718544, -0.0322751 , -0.0

In [29]:
model.predict(embedded_docs).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


(7, 8, 10)

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 8992, 3567, 9062, 5916], dtype=int32)